language: node_js
node_js:
  - '11'
script:
  - npx lerna run build
  - npm run lint
  - npm run test:coverage
  - npm run upload:coverage
deploy:
  provider: script
  script:
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    - npx lerna publish -y from-package
  skip_cleanup: true
  on:
    branch: master
    tags: true
