name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - run: yarn
      - run: yarn run lint
      - run: yarn run build
      - run: yarn run test

      - name: Publish to npm
        run: yarn run publish --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
