name: Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://node:13-alpine
    steps:
      - uses: actions/checkout@v1
      - run: apk add --no-cache git
      - run: yarn
      - run: yarn run lint
      - run: yarn run build
      - run: yarn run test:coverage
      - run: yarn run upload:coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn
      - run: yarn run build
      - run: yarn run publish ${GITHUB_REF:10} --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
