name: Release

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    # container: node:13-slim
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Publish
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          yarn
          yarn run build
          yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
