name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://node:13-alpine
    steps:
      - uses: actions/checkout@v1
      - run: apk add --no-cache git
      - run: yarn
      - run: yarn run lint
      - run: yarn run build
      - run: yarn run test:coverage
      - run: yarn run upload:coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}